---
title: "GSE66507"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
suppressPackageStartupMessages({
  library(SingleCellExperiment)
  library(scater)
  library(Matrix)
  library(ggplot2)
  library(dplyr)
  library(EnsDb.Hsapiens.v79)
})
```

```{r}
count = read.delim("../../Data/GSE66507/GSE66507_human_blastocyst_rnaseq_counts.txt", 
                   sep = "\t", row.names = 1)

ensemblID <- rownames(count)
geneIDs <- ensembldb::select(EnsDb.Hsapiens.v79, keys= ensemblID, keytype = "GENEID", columns = c("SYMBOL","GENEID"))

sum(is.na(geneIDs$SYMBOL))
sum(duplicated(geneIDs$SYMBOL))
geneIDs = geneIDs[!duplicated(geneIDs$SYMBOL),]

geneSymbol <- geneIDs$SYMBOL
names(geneSymbol) <- geneIDs$GENEID

onerow=geneSymbol[ensemblID]
sum(is.na(onerow))
count = count[!is.na(onerow),]
onerow = onerow[!is.na(onerow)]

rownames(count) <- onerow

celltype=gsub("[0-9.]", "", colnames(count))
cellname=colnames(count)
meta = data.frame(
  embryo = cellname,
  timepoint = rep("blastocyst", ncol(count)),
  celltype = celltype,
  type = rep("blastocyst", ncol(count)),
  dataset = rep("GSE66507", ncol(count))
)

sce = SingleCellExperiment::SingleCellExperiment(assay = list(counts = count),
                                                 colData = meta)
```

```{r}
totalUMI <- colSums(counts(sce))
#mitochondrial
propMito <- colSums(counts(sce)[grep("^MT", rownames(sce), value = TRUE), ])/totalUMI
propRibo <- colSums(counts(sce)[grep("^RP", rownames(sce), value = TRUE), ])/totalUMI
totalGene <- colSums(counts(sce) > 0)
propZero <- colSums(counts(sce) == 0)/nrow(sce)

sce$nUMI <- totalUMI
sce$nGene <- totalGene
sce$propMT <- colSums(counts(sce)[grep("^MT", rownames(sce), value = TRUE), ])/totalUMI
sce$propRibo <- colSums(counts(sce)[grep("^RP", rownames(sce), value = TRUE), ])/totalUMI

propZeroGene <- rowSums(counts(sce) == 0)/ncol(sce)
sce = sce[propZeroGene < 1, propZero < 1]
sce = scater::logNormCounts(sce)
sce = scater::runPCA(sce, scale = TRUE)
sce = scater::runUMAP(sce, ncomponents = 5)
plotUMAP(sce, colour_by = "celltype")

saveRDS(sce, file = "../Data/human_embryo_GSE66507.RDS")
```

```{r}
df = cbind(colData(sce), reducedDim(sce, "PCA"))
df <- as.data.frame(df)

idx = colnames(df)[8:10]
g <- lapply(idx, function(metric) {
  df$metric <- as.numeric(df[, metric])
  p <- df %>% ggplot(aes(x = PC1, y = PC2, col = metric)) +
    geom_point() 
  return(p)
})
patchwork::wrap_plots(g, ncol = 3)
```

```{r}
ggplot(df, aes(x = nGene, y = propMito, col = celltype)) + 
  geom_point()

ggplot(df, aes(x = nGene, fill = as.factor(celltype), alpha = 0.9)) + 
  geom_histogram(bins= 100) 
```

